version: "3"
services:
  db-legacy:
    image: postgres:14.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: db_legacy
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
  data-integration-service:
    depends_on:
      - db-legacy
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    # image: jorgelvelasquez/data-integration-service:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      PORT: ${PORT}
    container_name: data_integration_service
