name: Publish image Docker

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push image Docker to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Code review
        uses: actions/checkout@v2

      - name: Login in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/data-integration-service:latest
